### PR TITLE
Meeting minutes for 2021-11-09

### PR DESCRIPTION
**Pull request by ChristianKuehnel**

### CODE REVIEW

**Review by lazyparser — APPROVED** [review]
Thanks.

Any updates on the opSec topic https://github.com/llvm/llvm-iwg/issues/76 ?

**Comment by ChristianKuehnel** [comment]
> Any updates on the opSec topic #76 ?

No progress here. Nobody investigated this so far...

**Comment by lazyparser** [comment]
> > Any updates on the opSec topic #76 ?
> 
> No progress here. Nobody investigated this so far...

OK I'd like to do a few investigation at my spare time. But I'm not a security guy. It would be very helpful if someone w/ security background can get involved.

**Comment by lazyparser** [comment]
Since there was no other comments/reviews, I'd like to merge the minutes.

**Pull request merged**
